### ISSUE TITLE
PHP 8.2 compatible release

### ISSUE THREAD

**Issue by jraller** [php-amqp/php-amqp#424] opened 2023-01-23 19:24 UTC
Can a PHP 8.2 compatible release be issued?

**Comment by japodhidev** [comment] 2023-01-30 14:00
While waiting for an official release, I thought I might give building the extension from source a go. In case you are interested, I followed the instructions [here](https://www.php.net/manual/en/install.pecl.phpize.php).

**Comment by stlrnz** [comment] 2023-04-13 10:40
Are there any plans for a PHP 8.2 compatible release?

**Comment by yaotzin1** [comment] 2023-06-19 08:14
Is there any update... currently I am struggling with PHP 8.2 and I need to have PHP_AMQP installed for it.

**Comment by amber0612** [comment] 2023-07-07 13:21
Do we have an update on when we are going to release PHP8.2 compatible version?

**Comment by lyrixx** [comment] 2023-07-25 16:52
Fixed by #430 ?

**Comment by lstrojny** [comment] 2023-07-25 18:45
I will most likely need help with Windows, as I neither have a Windows dev box nor any idea what I am doing there. Any volunteers who know how to build a version on Windows? Even more applause for a PR to build on GitHub actions

**Comment by lstrojny** [comment] 2023-07-29 09:33
For everybody waiting for an 8.2 compatible release, [2.0.0alpha1 has been released](https://pecl.php.net/package/amqp/2.0.0alpha1).

I would really appreciate thorough testing with your real world workloads to find any regressions.

**Comment by lyrixx** [comment] 2023-07-29 09:47
I may be obvious, but there are BC Breaks 

## V1

```
>…ome/gregoire/dev/github.com/lyrixx/symfony(6.4) sudo \cp /usr/lib/php/20220829/amqp{-1,}.so

>…ome/gregoire/dev/github.com/lyrixx/symfony(6.4) MESSENGER_AMQP_DSN="amqp://127.0.0.1" ./phpunit src/Symfony/Component/Messenger/Bridge/Amqp/
PHPUnit 9.6.10 by Sebastian Bergmann and contributors.

Testing /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Bridge/Amqp
................................................................. 65 / 70 ( 92%)
.....                                                             70 / 70 (100%)

Time: 00:03.632, Memory: 14.00 MB

OK (70 tests, 145 assertions)
```
## V2

```
>…ome/gregoire/dev/github.com/lyrixx/symfony(6.4) sudo \cp /usr/lib/php/20220829/amqp{-2,}.so

>…ome/gregoire/dev/github.com/lyrixx/symfony(6.4) php --re amqp | head -n1
Extension [ <persistent> extension #20 amqp version 2.0.0dev ] {

>…ome/gregoire/dev/github.com/lyrixx/symfony(6.4) MESSENGER_AMQP_DSN="amqp://127.0.0.1" ./phpunit src/Symfony/Component/Messenger/Bridge/Amqp/
PHPUnit 9.6.10 by Sebastian Bergmann and contributors.

Testing /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Bridge/Amqp
.EEF............................................................. 65 / 70 ( 92%)
.....                                                             70 / 70 (100%)

Time: 00:01.535, Memory: 14.00 MB

There were 2 errors:

1) Symfony\Component\Messenger\Bridge\Amqp\Tests\Transport\AmqpExtIntegrationTest::testRetryAndDelay
TypeError: Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::ack(): Return value must be of type bool, null returned

/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:438
/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/AmqpReceiver.php:85
/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/AmqpExtIntegrationTest.php:100

2) Symfony\Component\Messenger\Bridge\Amqp\Tests\Transport\AmqpExtIntegrationTest::testRetryAffectsOnlyOriginalQueue
TypeError: Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::ack(): Return value must be of type bool, null returned

/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php:438
/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/AmqpReceiver.php:85
/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/AmqpExtIntegrationTest.php:303
/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/AmqpExtIntegrationTest.php:160

--

There was 1 failure:

1) Symfony\Component\Messenger\Bridge\Amqp\Tests\Transport\AmqpExtIntegrationTest::testItReceivesSignals
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
     "Symfony\\Component\\Messenger\\Stamp\\AckStamp"
 ]
 Done.
+
+Fatal error: Uncaught TypeError: Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::ack(): Return value must be of type bool, null returned in /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony
/Component/Messenger/Bridge/Amqp/Transport/Connection.php:438
+Stack trace:
+#0 /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/AmqpReceiver.php(85): Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection->ack()
+#1 /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Worker.php(217): Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpReceiver->ack()
+#2 /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Worker.php(171): Symfony\Component\Messenger\Worker->ack()
+#3 /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Worker.php(108): Symfony\Component\Messenger\Worker->handleMessage()
+#4 Standard input code(53): Symfony\Component\Messenger\Worker->run()
+#5 {main}
+  thrown in /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php on line 438
 '

/home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Bridge/Amqp/Tests/Transport/AmqpExtIntegrationTest.php:214

ERRORS!
Tests: 70, Assertions: 133, Errors: 2, Failures: 1.
>…ome/gregoire/dev/github.com/lyrixx/symfony(6.4)
```

and if I patch Symfony:
```diff
>…ome/gregoire/dev/github.com/lyrixx/symfony(6.4 *) git di
diff --git a/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php b/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php
index 6cdc7e00e9..cbed381dca 100644
--- a/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php
+++ b/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php
@@ -435,7 +435,7 @@ class Connection
 
     public function ack(\AMQPEnvelope $message, string $queueName): bool
     {
-        return $this->queue($queueName)->ack($message->getDeliveryTag());
+        return $this->queue($queueName)->ack($message->getDeliveryTag()) ?? true;
     }
 
     public function nack(\AMQPEnvelope $message, string $queueName, int $flags = \AMQP_NOPARAM): bool
```

tests are okay:
```
>…ome/gregoire/dev/github.com/lyrixx/symfony(6.4 *) MESSENGER_AMQP_DSN="amqp://127.0.0.1" ./phpunit src/Symfony/Component/Messenger/Bridge/Amqp/                                                                   
PHPUnit 9.6.10 by Sebastian Bergmann and contributors.                                                                                                                                                             
                                                                                                                                                                                                                   
Testing /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Messenger/Bridge/Amqp                                                                                                                   
................................................................. 65 / 70 ( 92%)                                                                                                                                   
.....                                                             70 / 70 (100%)                                                                                                                                   
                                                                                                                                                                                                                   
Time: 00:03.630, Memory: 14.00 MB                                                                                                                                                                                  
                                                                                                                                                                                                                   
OK (70 tests, 145 assertions)    
```

**Comment by lstrojny** [comment] 2023-07-29 12:37
@lyrixx thank you very much for testing Symfony messenger, it’s obviously one of the most important components. Since the patch is trivial, I would like to keep the change. Will you push the fix for messenger? Ideally there is already a compatible minor version out there once I release 2.0.0 stable.

**Comment by lyrixx** [comment] 2023-07-29 21:50
I'll do that, no problem

**Comment by lstrojny** [comment] 2023-07-30 20:48
[2.0.0alpha2](https://pecl.php.net/package/amqp/2.0.0alpha2) was released. Most relevant change is widened support for older versions of librabbitmq (>=0.8.0).

**Comment by stof** [comment] 2023-08-01 15:44
For a new major version, it would be great to have an upgrade guide detailing all the BC breaks being done.

**Comment by lstrojny** [comment] 2023-08-02 08:57
@stof would something like this be helpful and enough?

## `AMQPConnection` changes

### Method additions

 * `getConnectTimeout(): float`
 * `setConnectionName(string $connectionName): void`
 * `getConnectionName(): string`
### Type changes

```diff
- connect(): bool
+ connect(): void
```
```diff
- disconnect(): bool
+ disconnect(): void
```
```diff
- pconnect(): bool
+ pconnect(): void
```
```diff
- pdisconnect(): bool
+ pdisconnect(): void
```
```diff
- reconnect(): bool
+ reconnect(): void
```
```diff
- preconnect(): bool
+ preconnect(): void
```
```diff
- setHost(string $host): bool
+ setHost(string $host): void
```
```diff
- setLogin(string $login): bool
+ setLogin(string $login): void
```
```diff
- setPassword(string $password): bool
+ setPassword(string $password): void
```
```diff
- setPort(int $port): bool
+ setPort(int $port): void
```
```diff
- setVhost(string $vhost): bool
+ setVhost(string $vhost): void
```
```diff
- setTimeout(float $timeout): bool
+ setTimeout(float $timeout): void
```
```diff
- setReadTimeout(float $timeout): bool
+ setReadTimeout(float $timeout): void
```
```diff
- setWriteTimeout(float $timeout): bool
+ setWriteTimeout(float $timeout): void
```
```diff
- setRpcTimeout(float $timeout): bool
+ setRpcTimeout(float $timeout): void
```
```diff
- setCACert(string $cacert): unknown
+ setCACert(string $cacert): void
```
```diff
- setCert(string $cert): unknown
+ setCert(string $cert): void
```
```diff
- setKey(string $key): unknown
+ setKey(string $key): void
```
```diff
- setVerify(bool $verify): unknown
+ setVerify(bool $verify): void
```
```diff
- setSaslMethod(int $method): unknown
+ setSaslMethod(int $saslMethod): void
```

**Comment by stof** [comment] 2023-08-02 08:58
@lstrojny yes, that's quite helpful.

**Comment by lstrojny** [comment] 2023-08-02 11:09
[UPGRADING.md](https://github.com/php-amqp/php-amqp/blob/latest/UPGRADING.md) has landed

**Comment by Jan-E** [comment] 2023-08-03 03:07
> I will most likely need help with Windows, as I neither have a Windows dev box nor any idea what I am doing there. Any volunteers who know how to build a version on Windows? Even more applause for a PR to build on GitHub actions

I am always building php_amqp.dll with some patches. And publish my builds with a few other extensions on https://www.apachelounge.com/viewforum.php?f=6

The new version broke my builds for php 8.2.9 and php 8.3.beta2, because from PHP 8.2 upwards `main/php_stdint.h` does not exist anymore. See for instance https://github.com/php-amqp/php-amqp/blob/latest/amqp.c#L35
You will have to use `<stdint.h>` there. And on 7 other places.
Do you want me to create a PR? These are the necessary changes:
```
diff --git a/amqp.c b/amqp.c
index 2d9bf48..d3e77fe 100644
--- a/amqp.c
+++ b/amqp.c
@@ -32,7 +32,7 @@
 
 #ifdef PHP_WIN32
     #if PHP_VERSION_ID >= 80000
-        #include "main/php_stdint.h"
+        #include <stdint.h>
     #else
         #include "win32/php_stdint.h"
     #endif
diff --git a/amqp_basic_properties.c b/amqp_basic_properties.c
index 54ea02b..bf92ab1 100644
--- a/amqp_basic_properties.c
+++ b/amqp_basic_properties.c
@@ -40,7 +40,7 @@
 #ifdef PHP_WIN32
     #include "win32/unistd.h"
     #if PHP_VERSION_ID >= 80000
-        #include "main/php_stdint.h"
+        #include <stdint.h>
     #else
         #include "win32/php_stdint.h"
     #endif
diff --git a/amqp_channel.c b/amqp_channel.c
index 5fa92e7..d48f0d1 100644
--- a/amqp_channel.c
+++ b/amqp_channel.c
@@ -30,7 +30,7 @@
 
 #ifdef PHP_WIN32
     #if PHP_VERSION_ID >= 80000
-        #include "main/php_stdint.h"
+        #include <stdint.h>
     #else
         #include "win32/php_stdint.h"
     #endif
diff --git a/amqp_connection.c b/amqp_connection.c
index 40c2859..2aaf63f 100644
--- a/amqp_connection.c
+++ b/amqp_connection.c
@@ -32,7 +32,7 @@
 
 #ifdef PHP_WIN32
     #if PHP_VERSION_ID >= 80000
-        #include "main/php_stdint.h"
+        #include <stdint.h>
     #else
         #include "win32/php_stdint.h"
     #endif
diff --git a/amqp_connection_resource.c b/amqp_connection_resource.c
index 18cbf00..7cf2abb 100644
--- a/amqp_connection_resource.c
+++ b/amqp_connection_resource.c
@@ -31,7 +31,7 @@
 
 #ifdef PHP_WIN32
     #if PHP_VERSION_ID >= 80000
-        #include "main/php_stdint.h"
+        #include <stdint.h>
     #else
         #include "win32/php_stdint.h"
     #endif
diff --git a/amqp_envelope.c b/amqp_envelope.c
index c817c0b..748a104 100644
--- a/amqp_envelope.c
+++ b/amqp_envelope.c
@@ -29,7 +29,7 @@
 
 #ifdef PHP_WIN32
     #if PHP_VERSION_ID >= 80000
-        #include "main/php_stdint.h"
+        #include <stdint.h>
     #else
         #include "win32/php_stdint.h"
     #endif
diff --git a/amqp_exchange.c b/amqp_exchange.c
index bd7f623..6c2ae5a 100644
--- a/amqp_exchange.c
+++ b/amqp_exchange.c
@@ -29,7 +29,7 @@
 
 #ifdef PHP_WIN32
     #if PHP_VERSION_ID >= 80000
-        #include "main/php_stdint.h"
+        #include <stdint.h>
     #else
         #include "win32/php_stdint.h"
     #endif
diff --git a/amqp_queue.c b/amqp_queue.c
index a6990df..5fb1027 100644
--- a/amqp_queue.c
+++ b/amqp_queue.c
@@ -30,7 +30,7 @@
 
 #ifdef PHP_WIN32
     #if PHP_VERSION_ID >= 80000
-        #include "main/php_stdint.h"
+        #include <stdint.h>
     #else
         #include "win32/php_stdint.h"
     #endif
```

**Comment by Jan-E** [comment] 2023-08-03 03:29
Example for PHP 8.2.9 NTS x64:
https://phpdev.toolsforresearch.com/php-8.2.9-nts-Win32-vs16-x64.htm
https://phpdev.toolsforresearch.com/php-8.2.9-nts-Win32-vs16-x64.zip

**Comment by lstrojny** [comment] 2023-08-03 06:18
@Jan-E thank you very much, I applied the patch. You don’t happen to have skill, time and energy to help with a GitHub action build for Windows? I would love to not break Windows builds every 3rd commit or so 🤕

**Comment by lstrojny** [comment] 2023-08-15 22:12
[2.0.0RC1](https://pecl.php.net/package/amqp/2.0.0RC1) has landed. This is supposed to be the last version before GA.

Feedback more than welcome!

**Comment by lstrojny** [comment] 2023-08-20 11:15
[2.0.0 has been released](https://pecl.php.net/package/amqp/2.0.0).

Now closing this issue

**Closed by lstrojny** 2023-08-20 11:15 UTC

**Comment by xorgxx** [comment] 2023-08-30 19:07
hi, how we can use on windows ? thank

**Comment by Jan-E** [comment] 2023-08-30 21:53
If compiling it yourself is above your head: download php_amqp.dll inside the zips on https://www.apachelounge.com/viewtopic.php?t=6359

**Comment by xorgxx** [comment] 2023-08-31 07:12
@Jan-E Thank's

**Comment by lstrojny** [comment] 2023-08-31 08:08
To give @Jan-E efforts a bit more visibility, I’ve created an [announcement thread](https://github.com/php-amqp/php-amqp/discussions/477). Thanks for your work, @Jan-E
