### ISSUE TITLE
AMQPException: Library error: a socket error occurred 

### ISSUE THREAD

**Issue by huangfeng123** [php-amqp/php-amqp#258] opened 2016-12-01 01:08 UTC
Hi, i got a lot of 'Library error: a socket error occurred ' when i set heartbeat values to 6 , when i restart rabbitmq server and never restart the php-fpm  i got the error too; i try to catche the exception but no luck , i try https://github.com/pdezwart/php-amqp/issues/192 , but doesn't work too, I do not know what to do now

 uname -a
Linux localhost.localdomain 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

php --ri amqp

amqp

Version => 1.7.1
Revision => release
Compiled => Nov  4 2016 @ 18:54:52
AMQP protocol version => 0-9-1
librabbitmq version => 0.8.1-pre
Default max channels per connection => 256
Default max frame size => 131072
Default heartbeats interval => 0

Directive => Local Value => Master Value
amqp.host => localhost => localhost
amqp.vhost => / => /
amqp.port => 5672 => 5672
amqp.timeout => no value => no value
amqp.read_timeout => 0 => 0
amqp.write_timeout => 0 => 0
amqp.connect_timeout => 0 => 0
amqp.login => guest => guest
amqp.password => guest => guest
amqp.auto_ack => 0 => 0
amqp.prefetch_count => 3 => 3
amqp.channel_max => 256 => 256
amqp.frame_max => 131072 => 131072
amqp.heartbeat => 0 => 0

**Comment by pinepain** [comment] 2016-12-01 11:44
Hi! Does reloading php-fpm solves the issue? What PHP and RabbitMQ version do you use? Also, it would help a loot if you share minimal example to reproduce the issue you see alongside with step by step instruction to reproduce it.

**Comment by huangfeng123** [comment] 2016-12-01 12:55
@pinepain  yes, reloading php-fpm can solves the issue;  php version is 7.0.6 and rabbitmq version is 3.6.5; 
when i run the code as follows i get the error. thanks 

$conn_args = array(
	'host' => '192.168.204.72',
	'port' => '5672',
	'login' => 'root',
	'password' => 'root',
	'heartbeat' => 6
	);
$conn = new AMQPConnection($conn_args);
if ($conn->pconnect()) {
    echo "Established a connection to the broker \n";
} else {
    echo "Cannot connect to the broker \n ";
}
$channel = new AMQPChannel($conn);

$ex = new AMQPExchange($channel);
$ex->setName('exchange33');
$ex->setType(AMQP_EX_TYPE_DIRECT);
$ex->setFlags(AMQP_DURABLE);

echo "exchange status:".$ex->declareExchange();
echo "\n";

$queue = new AMQPQueue($channel);
$queue->setName('queue33');
      $queue->setFlags(AMQP_NOPARAM);
      $queue->declareQueue();
      $queue->bind('exchange33','key');

$message = json_encode(array('Hello World3!','php3','c++3:'));
$routingkey='key';	  
$res = $ex->publish($message,$routingkey);


php -version

PHP 7.0.6 (cli) (built: Jun  4 2016 13:48:07) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans

rabbitmqctl status

Status of node rabbit@localhost ...
[{pid,27552},
 {running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.6.5"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.6.5"},
      {rabbit,"RabbitMQ","3.6.5"},
      {os_mon,"CPO  CXC 138 46","2.4.1"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.6.5"},
      {webmachine,"webmachine","1.10.3"},
      {mochiweb,"MochiMedia Web Server","2.13.1"},
      {ssl,"Erlang/OTP SSL application","8.0.2"},
      {public_key,"Public key infrastructure","1.2"},
      {crypto,"CRYPTO","3.7.1"},
      {amqp_client,"RabbitMQ AMQP Client","3.6.5"},
      {rabbit_common,[],"3.6.5"},
      {compiler,"ERTS  CXC 138 10","7.0.2"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.2.1"},
      {asn1,"The Erlang ASN1 compiler version 4.0.4","4.0.4"},
      {syntax_tools,"Syntax tools","2.1"},
      {inets,"INETS  CXC 138 49","6.3.3"},
      {xmerl,"XML parser","1.3.12"},
      {mnesia,"MNESIA  CXC 138 12","4.14.1"},
      {sasl,"SASL  CXC 138 11","3.0.1"},
      {stdlib,"ERTS  CXC 138 10","3.1"},
      {kernel,"ERTS  CXC 138 10","5.1"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang/OTP 19 [erts-8.1] [source-77fb4f8] [64-bit] [smp:4:4] [async-threads:64] [hipe] [kernel-poll:true]\n"},
 {memory,
     [{total,59202976},
      {connection_readers,0},
      {connection_writers,0},
      {connection_channels,0},
      {connection_other,2832},
      {queue_procs,209624},
      {queue_slave_procs,0},
      {plugins,602808},
      {other_proc,19381184},
      {mnesia,82456},
      {mgmt_db,509904},
      {msg_index,48168},
      {other_ets,1515968},
      {binary,34472},
      {code,24815589},
      {atom,1033401},
      {other_system,10966570}]},
 {alarms,[]},
 {listeners,[{clustering,25672,"::"},{amqp,5672,"::"}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,3301144985},
 {disk_free_limit,50000000},
 {disk_free,52243738624},
 {file_descriptors,
     [{total_limit,102300},
      {total_used,3},
      {sockets_limit,92068},
      {sockets_used,0}]},
 {processes,[{limit,1048576},{used,236}]},
 {run_queue,0},
 {uptime,39},
 {kernel,{net_ticktime,60}}]

**Comment by lstrojny** [comment] 2017-03-23 18:49
@huangfeng123 did you try this with the latest 1.9.0?

**Comment by huangfeng123** [comment] 2017-03-30 01:38
@lstrojny Hi , I have tried it， but it does't work too.  I restart the rabbitmq_server , doesn't restart php-fpm , when the rabbitmq pconnection num  less than  php-fpm num , i will get the error.  But short connect doesn't has this question .

thanks~

**Comment by jippi** [comment] 2017-03-30 07:55
I'm seeing the same issue from cli apps

**Comment by huangfeng123** [comment] 2017-03-31 01:53
@jippi Hi, is there a solution ? can you provide URL. thanks ~

**Comment by ambrous** [comment] 2017-05-11 15:54
I had the same error and a reducing of prefetch count solved it. I set prefetch_count to 1 (3 by default)

I read a rabbit server error log and after found this: http://stackoverflow.com/questions/35438843/rabbitmq-error-timeout

**Comment by EagleEyeJohn** [comment] 2017-12-01 11:08
@ambrous thanks. the same solution has worked for us too (using 1.9.3 with php 5.6.31).  we were unable to ack() or nack() messages, which caused them to be redelivered (flag on message was then set to true)

**Comment by c-datculescu** [comment] 2017-12-07 11:51
Hello all.

I have encountered the same issue and i think i might have been able to reduce it to a certain point.

I am also able to consistently reproduce the issue using simple publisher/consumer setup.

The setup is the following:
I have a queue, containing 1000 messages that are around 124000 bytes in size.
I am launching a consumer with prefetchCount of 100.
The consumer is in ack mode, and we have a sleep in between each message processing of 15 seconds, ack happening after the message has been processed (we simulate this way heavy message processing that we have on the live system).
After the third message generally, with this parameters, the consumer dies with a socket error.
The error is reproducible from librabbitmq 0.5.2 up till librabbitmq 0.8.0, and with php-amqp from 1.4.0 to 1.7.1.

The error on librabbitmq 0.5.2 and php-amqp 1.4.0 is `Error: Could not ack message, error code=-9`, error on higher versions is just a normal socket error.

The error on rabbitmq side is closed with `{writer,send_failed,{error,timeout}}`.

What i have noticed, especially with these large messages, we have a decent number of dropped packets. Increasing the queue length helps somehow the issue, but even at a queue length of 100000 it still eventually crashes.

We took also a tcpdump on a machine not running any other service for the communication happening between client and server, and the server eventually sends a RST packet, closing the connection.

What helps the issue is lowering the prefetchCount (but not setting it necessarily to 1, the value is dependant on the size of the messages currently in the queue), sending smaller messages and having smaller times for processing the messages.

I hope this somehow helps troubleshooting the issue to some extent.

The tests were ran on ubuntu xenial, linux mint, debian 8 and mac osx sierra (with the same reproducible results).

**Comment by pinepain** [comment] 2017-12-07 12:02
@c-datculescu thanks a lot for such important details. I think it may be the same issue, at least symptoms are very similar. Do you have a chance to verify whether it still present in php-amqp v1.9.3?

**Comment by c-datculescu** [comment] 2017-12-07 12:17
I will give it a try today or tomorrow and come back with the details.

**Comment by c-datculescu** [comment] 2017-12-07 12:33
A small clarification since it is not obvious from my report: when increasing the queue length i am talking about txqueuelen from the network interface. As a side observation, playing with the MTU also does not impact the tests in any way.

**Comment by c-datculescu** [comment] 2017-12-08 20:39
Hi guys. 

I can confirm the error still happens with both 1.9.3 and 1.9.4 dev version.

If i am correct in understanding the issue, i doubt that it can be fixed in php-amqp but rather looks like it might belong to librabbitmq-c. The test was done with librabbitmq-c 0.7.0, but i will try with the latest stable from there as well and get back with results.

**Comment by Gamesh** [comment] 2019-06-05 11:16
i encountered the same problem yesterday and some notes form my side that solved the issue for me, it might help others as well as i've seen some are using the heartbeat setting.

So little bit of context, there is a amqp.heartbeat setting:

> The timeout is in seconds, and default value is 60. Older releases used 580 seconds by default.

it's not exactly the same thing as a keepalive

> Heartbeat frames are sent about every heartbeat timeout / 2 seconds. This value is sometimes referred to as the heartbeat interval. After two missed heartbeats, the peer is considered to be unreachable

so for example when debugging i had these socket errors i guess because the heartbeat was not sent because of blocking and the broker closes the connection, might also happen in long running jobs.

Also note that changing heartbeat in php.ini won't necessarily change it for a connection this is because broker negotiates it with the client and chooses the lowest value. So if PHP client has heartbeat 6 and broker 30 it will be 6 for the connection. You need to increase it at both sides the client and the broker.

> The broker and client will attempt to negotiate heartbeats by default. When both values are non-0, the lower of the requested values will be used. If one side uses a zero value (attempts to disable heartbeats) but the other does not, the non-zero value will be used.

For my case when changed to a high enough value like 180 on both client and broker i stopped receiving this error, because the server just waits longer before assuming that the connection is dead. You can see the actual Hearbeat per connection in the UI connections tab if you add a column Heartbeats.

Hope it helps somebody

**Comment by lstrojny** [comment] 2023-08-02 21:31
Closing, as there is nothing specific to be done here.

**Closed by lstrojny** 2023-08-02 21:31 UTC
