### ISSUE TITLE
How to fetch an existing persistent connection

### ISSUE THREAD

**Issue by SyuTingSong** [php-amqp/php-amqp#308] opened 2018-01-03 04:16 UTC
As soon as calling `AMQPConnection::pconnect()`, an exception with message "There are already established persistent connection to the same resource" is thrown. Maybe the persistent connection is created by some other libs, is there any way to fetch the connected AMQPConnection instance?

**Comment by pinepain** [comment] 2018-01-05 19:55
Hi! Sorry for late reply. It should not be this way afair, `AMQPConnection::pconnect()` should fetch that persistent connection unless some error occurs. Do you have a standalone code that allows to reproduce the issue? Also, what php-amqp and what php version do you and on what platform? Providing more details as per [How to report a problem](https://github.com/pdezwart/php-amqp#how-to-report-a-problem) guide may help others to help you to troubleshoot the issue.

**Comment by SyuTingSong** [comment] 2018-01-09 05:38
Hi, thanks for replying.

Because I am not sure such exception is a bug or just being misused. So I directly ask.

The code to reproduce the issue is:
```php
<?php
ini_set('display_errors', 'on');
$con1 = new AMQPConnection();
$con1->setHost('rabbitmq');
$con1->pconnect();
$con2 = new AMQPConnection();
$con2->setHost('rabbitmq');
$con2->pconnect();
```
The error output:
```
Fatal error: Uncaught AMQPConnectionException: There are already established persistent connection to the same resource. in /a.php:8
Stack trace:
#0 /a.php(8): AMQPConnection->pconnect()
#1 {main}
  thrown in /a.php on line 8
```
The php version I used:
```
PHP 7.1.11 (cli) (built: Jan  8 2018 07:05:02) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.11, Copyright (c) 1999-2017, by Zend Technologies
```
The AMQP extension I used:
```
amqp

Version => 1.9.3
Revision => release
Compiled => Jan  8 2018 @ 07:07:48
AMQP protocol version => 0-9-1
librabbitmq version => 0.8.0
Default max channels per connection => 256
Default max frame size => 131072
Default heartbeats interval => 0

Directive => Local Value => Master Value
amqp.host => localhost => localhost
amqp.vhost => / => /
amqp.port => 5672 => 5672
amqp.timeout => no value => no value
amqp.read_timeout => 0 => 0
amqp.write_timeout => 0 => 0
amqp.connect_timeout => 0 => 0
amqp.login => guest => guest
amqp.password => guest => guest
amqp.auto_ack => 0 => 0
amqp.prefetch_count => 3 => 3
amqp.channel_max => 256 => 256
amqp.frame_max => 131072 => 131072
amqp.heartbeat => 0 => 0
amqp.cacert => no value => no value
amqp.cert => no value => no value
amqp.key => no value => no value
amqp.verify => 1 => 1
```

**Comment by pinepain** [comment] 2018-01-09 07:29
Hi @SyuTingSong!

What you see with unable two identical persistent connecting to the same host with the same credentials is expected and is a current limitation of how persistent amqp connection is implemented. This and other limitations are briefly covered under [Persistent connection](https://github.com/pdezwart/php-amqp#persistent-connection) readme section and if you need to clarify some details in advance it's more than welcomed to ask 😃 .

Without going deep into how pconnect is implemented, the concept around it was to get the best possible performance with amqp and from this perspective you are more likely want to have a single persistent connection to unique resource.

### There is a hackish way to avoid this limitation:

Persistent connection uniqueness is checked against [large number of parameters](https://github.com/pdezwart/php-amqp/blob/6c59bcbd6e63d72cd32ead0f969d70970ad6bad7/amqp_connection.c#L98-L105), among which are `channel_max`, `frame_max` and `heartbeat` which could be customized and passed to [AMQPConnection::__construct()](https://github.com/pdezwart/php-amqp/blob/6c59bcbd6e63d72cd32ead0f969d70970ad6bad7/stubs/AMQPConnection.php#L38-L44) to get new unique persistent connection. You may avoid setting  `hearbeat` to prevent your persistent connection been closed from server side if there would be no activity on the channel, though, it's up to you and heavily depends on your app load. Setting `channel_max` and `frame_max` for persistent connection (large enough to avoid disruptions) looks like a safer approach. Note, that you have to handle that in your code and be totally sure you need that.

**Comment by SyuTingSong** [comment] 2018-01-18 06:23
I read the persistent connection limitation in readme. But I still not understand why php-amqp doesn't work as other libs that support pconnect, e.g. redis, mysqli, memcache... Instead of throwing an Exception, just pick-up an existing connection to use when persistent-hash is the same.

The hackish way you suggested above creates another connection. Seems that still can't reuse the existing connection.

**Comment by pinepain** [comment] 2018-01-18 19:06
@SyuTingSong At the time I was facing the choice to pick opened `pconnect` connection that matches the hash, I decided to not to because of how AMQP protocol designed and because of potential unintentional side effects sharing between both logical connection: e.g. you publish in one logical connection and because publish is async operation you may get an error propagated in another logical connection. There are other edge cases which falls into this or similar issue. While channel separation could be managed for two logical connection somehow, it won't help solving connection-level AMQP errors handling properly. Explicit is better than implicit (PEP 20 in action, right?).

**Comment by Tobion** [comment] 2019-07-11 01:07
hello @pinepain. I don't understand how persistent connections are meant to be used. 
If you consume messages from several workers from the PHP CLI, it means there are different PHP processes that open a connection. But persistent connections are not shared between different php processes, are they?
So if they are not shared, then the only use-case would be to use persistent connections from the same php process. But you cannot use persistent connections to the same host (connection params). When would I use persistent connections then? I would really appreciate an explanation.

**Comment by pinepain** [comment] 2019-07-11 07:40
Persistent connections here works the same way as persistent db connection - https://www.php.net/manual/en/features.persistent-connections.php.

**Comment by Tobion** [comment] 2019-07-11 20:21
Thanks for the link. As I assumed, for the CLI there is no point in using persistent connections. It's only relevant for web processes.

**Comment by pinepain** [comment] 2019-07-12 08:09
Yeah, there is no benefit to use persistent connection in CLI unless different part of the code constantly open and close that connection.

**Comment by lstrojny** [comment] 2021-12-01 11:20
Closing

**Closed by lstrojny** 2021-12-01 11:20 UTC
