### ISSUE TITLE
Error "second 'channel.open' seen" with persistent connections

### ISSUE THREAD

**Issue by ErwinSteffens** [php-amqp/php-amqp#297] opened 2017-11-16 13:01 UTC
We see errors occurring with this library when creating the channel object. The error is:

`AMQPConnectionException: Server connection error: 504, message: CHANNEL_ERROR - second 'channel.open'`

We hope you can help us to track down this error because we cannot find out why it happens. We see it in our production environment but were not able to reproduce it in development.

Our code for publishing basically looks like below (cannot post the full code here). We are sure we only use the `getInstance()` method for creating this component and this is the only point in which we handle AMQP stuff. We call this code from the `register_shutdown_function` but I do not think this is related.

```php
class AmqpComponent
{
    private static $instance;

    public static function getInstance(): AmqpComponent
    {
        if ( !self::$instance )
        {
            self::$instance = new AmqpComponent();
        }
        return self::$instance;
    }

    private $connection;
    private $channel;

    private function __construct()
    {
        $amqpConfig[ 'host' ] = 'our-host';
        $amqpConfig[ 'port' ] = 'port';
        $amqpConfig[ 'login' ] = 'login';
        $amqpConfig[ 'password' ] = 'password';

        $this->connection = new AMQPConnection( $amqpConfig );
        $this->connection->pconnect();

        $this->channel = new AMQPChannel( $this->connection );
    }

    public function publish( AmqpMessage $msg )
    {
        $data = json_encode( $msg->getData() );

        $exchangeName = $this->getExchangeName( $msg );
        $attributes = $this->getMessageAttributes( $msg );
        $routingKey = $this->getMessageRoutingKey( $msg );

        $exchange = new AMQPExchange( $this->channel );
        $exchange->setName( $exchangeName );

        $routingKey = 'msg';
        return $exchange->publish( $data, $routingKey, AMQP_MANDATORY, $attributes );
    }
}
```

The full exception we get:

```
AMQPConnectionException: Server connection error: 504, message: CHANNEL_ERROR - second 'channel.open' seen
    @ src/com/components/amqp/AmqpComponent.php:51
    ↳ AMQPChannel->__construct(AMQPConnection) @ src/com/components/amqp/AmqpComponent.php:51;
    ↳ com\components\amqp\AmqpComponent->__construct() @ src/com/components/amqp/AmqpComponent.php:27;
    ↳ com\components\amqp\AmqpComponent::getInstance() @ src/com/components/comm/SendingComponent.php:54;
    ↳ com\components\comm\SendingComponent->send() @ src/com/components/comm/commComponentFactory.php:38;
    ↳ com\components\comm\SendingComponent::sendNotifications() @ src/com/components/comm/commComponentFactory.php:24;
    ↳ com\components\comm\SendingComponent::com\components\comm\{closure}() @ :n/a;
```

Version/configuration information:

Version: 1.9.3
Revision: release
Compiled: Oct 19 2017 @ 17:39:52
AMQP protocol version: 0-9-1
librabbitmq version: 0.8.0
Default max channels per connection: 256
Default max frame size: 131072
Default heartbeats interval: 0

We hope you can help us or point us in the right direction.

**Comment by pinepain** [comment] 2017-11-16 13:53
Hi! Looks like a bug. Could provide a minimal code to reproduce the issue?

**Comment by ErwinSteffens** [comment] 2017-11-16 14:59
We do not have a real reproduction that we can share. We will try to find one.

**Comment by pinepain** [comment] 2017-11-16 15:38
Do you have a chance to experiment with xdebug and opcache toggled on/off? Also, could you please provide your OS, platform, PHP version and a way it was installed?

**Comment by ErwinSteffens** [comment] 2017-11-16 15:52
I think xdebug and opcache are no option, but I will discuss it tomorrow.

OS version is CentOS 7.4.1708, PHP Version is 7.1.11. It was installed through the Remi repositories (https://rpms.remirepo.net/).

**Comment by ErwinSteffens** [comment] 2017-11-16 19:00
Debugging in production is not an option because we have a lot of traffic.

One question: Do we have to close the channel after usage? I see a `close` method on the AMQPChannel class but it is not in the documentation.

**Comment by ErwinSteffens** [comment] 2017-11-16 19:39
Shouldn't the `php_amqp_connection_resource_get_available_channel_id` be thread-safe when using persistent connections? You get the same connection resource for each channel I think?

**Comment by pinepain** [comment] 2017-11-16 20:51
Connection is thread-specific, you can't share any of it child resources (channel, queue, exchange) between threads. Also, the extension is not designed with been thread-safe in mind. While it may work, I didn't test it for that and not aware whether anybody else did. I had a client who was using php-amqp with pthread, however they quickly moved from it to forks.

`close` method should be a part of class public API, at least I see in stubs - https://github.com/pdezwart/php-amqp/blob/99db17b36762dc05ebefc2ecf762d0abeb42bdd5/stubs/AMQPChannel.php#L44-L49 or you mean some other docs?

Normally, you amqp channel closed when it correspondent PHP object dtored. The `close` method is optional, it primary use is when you want to close channel before `AMQPChannel` object get destructed (in terms of PHP internals, when it's `free` function invoked). 

Answering you question about closing channel, you may do that, but as written above, if channel object destructed, you should be safe. It means that all queues and exchanges that use that channel should be destructed too, so if you need to get job done, try to `close()` it, if it will do the job it will at least let you move forward while someone will find a chance to track down the underlying issue.

**Comment by ErwinSteffens** [comment] 2017-11-17 09:52
Ok, is understand now. I thought it was reusing the connections over PHP processes, but there is a connection per proces. 

The `close` method was not in the stubs used by PHPStorm so we did not find it. We have added it, but it does not resolve the issue.

**Comment by ErwinSteffens** [comment] 2017-11-20 19:50
We are seeing it in our dev vagrant machine now, so we can try to debug it. I do not know a precise scenario, so I can't give you are working example which shows this error.

I am trying to build the extension now and include some logging on the channel opening proces. I've build and installed the `librabbitmq` v0.8 and have build and installed extension, but we are getting a segfault now when running it. I think it is related to not picking up the latest librabbitmq version. 

This is our output from `php --ri amqp` which shows an old version of the lib being used. Any suggestions on how to fix this?

```
amqp

Version => 1.9.4-dev
Revision => release
Compiled => Nov 20 2017 @ 20:28:32
AMQP protocol version => 0-9-1
librabbitmq version => 0.5.2
Default max channels per connection => 256
Default max frame size => 131072
Default heartbeats interval => 0

Directive => Local Value => Master Value
amqp.host => localhost => localhost
...
```

**Comment by ErwinSteffens** [comment] 2017-11-21 09:29
Got a little further. Removed the librabbitmq files installed by the package manager and build and installed in from source. The library now builds and installs, but when starting I get:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/amqp.so' - librabbitmq.so.4: cannot open shared object file: No such file or directory in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/amqp.so' - librabbitmq.so.4: cannot open shared object file: No such file or directory in Unknown on line 0
```

**Comment by ErwinSteffens** [comment] 2017-11-21 09:53
Ok, forgot the last comment. Got it working now. Trying to reproduce the error now and see what happens...

**Comment by pinepain** [comment] 2017-11-21 12:16
As to librabbitmq installation, during manual install it should show you the path it install to in cli output. You may use `rpath` to see what path `amqp.so` looks for libraries, I guess.

The `second 'channel.open' seen` error looks like internal extension bug, so I wouldn't expect much from xdebug. If you will be able to provide public with a standalone script it may help. Apart of that less likely someone will have a clue about how to trace it downs.

If you have proprietary code which you can't share with public or there is no reasonable way to strip down it to reproducible example, feels free to offer sponsorship and I'm pretty sure the debugging could be done with NDA signed. I personally wouldn't refuse a bounty to hunt down this issue.

**Comment by ErwinSteffens** [comment] 2017-11-21 14:32
We have found the issue. Due to a bug in our code we were publishing some messages to a not existing exchange. This seems to cause a the issue with message published after this error. We have created the exchange and this has solved the problem for us.

It can be reproduced by running the following script: 

```php
<?php

$connection = new AMQPConnection();
$connection->pconnect();

$channel = new AMQPChannel($connection);

$exchange = new AMQPExchange($channel);
$exchange->setName("exchange1");
$exchange->setType(AMQP_EX_TYPE_DIRECT);
$exchange->declareExchange();

$exchangeName = "exchange" . rand(1, 2);
$exchange = new AMQPExchange($channel);
$exchange->setName($exchangeName);
$exchange->publish("test");

$channel->close();
```

You have to run it concurrent. We do it by using the `loadtest` package (https://www.npmjs.com/package/loadtest) and running it with:

`loadtest -n 100 -c 5 -k http://192.168.33.10/run.php`

When enabling the error logging in the vagrant machine the following error shows up:

```
2017/11/21 14:21:56 [error] 3284#3284: *200 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught AMQPConnectionException: Server connection error: 504, message: CHANNEL_ERROR - second 'channel.open' seen in /var/www/html/run.php:6
Stack trace:
#0 /var/www/html/run.php(6): AMQPChannel->__construct(Object(AMQPConnection))
#1 {main}
```

I can try to create a fix, but I have no deep knowledge of the amqp protocol or rabbitmq so I think it will be a little difficult for me.

**Comment by ErwinSteffens** [comment] 2017-11-21 19:04
Just a little extra info. We had a tshark dump which displays the following pattern:

<img width="1300" alt="screen shot 2017-11-21 at 20 01 37" src="https://user-images.githubusercontent.com/6931114/33091297-fb00a690-cef6-11e7-8a3a-e8ffe25e347a.png">

And the details of the selected error:

<img width="981" alt="screen shot 2017-11-21 at 20 01 50" src="https://user-images.githubusercontent.com/6931114/33091317-098da2da-cef7-11e7-9c40-1840f33e3da2.png">

**Comment by pinepain** [comment] 2017-11-21 20:23
Publishing to nonexistent exchange leads to AMQP channel-level error, so what you see is expected.

**Comment by pinepain** [comment] 2017-11-21 20:27
@ErwinSteffens I guess you are using PHP non-cli SAPI, right? Could you please share your setup?

**Comment by ErwinSteffens** [comment] 2017-11-21 20:31
We see the actual "second 'channel.open' seen" error later on when publishing to an existing exchange. 

<img width="1132" alt="screen shot 2017-11-21 at 21 26 57" src="https://user-images.githubusercontent.com/6931114/33095152-e608c3c4-cf02-11e7-96c4-b22e26e8b17e.png">

We are running it with php-fpm behind nginx.

**Comment by pinepain** [comment] 2017-11-22 09:49
It looks like channel is not properly closed. It might be a bug in error handling or in channel opening/closing or both.

**Closed** 2023-08-15 10:01 UTC
