### ISSUE TITLE
compilation with-lib dir not handeled correctly

### ISSUE THREAD

**Issue by mokraemer** [php-amqp/php-amqp#419] opened 2022-07-22 11:56 UTC
configure adds /usr 2x:

`./configure --host=x86_64-mageia-linux-gnu --build=x86_64-mageia-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-php-config=/usr/bin/php-config --with-libdir=lib64 --with-amqp=shared,/usr`

results in
`/bin/sh /home/marc/rpms/all-pecl/php-amqp/BUILD/amqp-1.11.0/libtool --mode=link cc -shared -I/home/marc/rpms/all-pecl/php-amqp/BUILD/amqp-1.11.0/include -I/home/marc/rpms/all-pecl/php-amqp/BUILD/amqp-1.11.0/main -I/home/marc/rpms/all-pecl/php-amqp/BUILD/amqp-1.11.0 -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables -D_GNU_SOURCE  -Wl,--as-needed -Wl,-z,relro -Wl,-O1 -Wl,--build-id=sha1 -Wl,--enable-new-dtags  -o amqp.la -export-dynamic -avoid-version -prefer-pic -module -rpath /home/marc/rpms/all-pecl/php-amqp/BUILD/amqp-1.11.0/modules  amqp.lo amqp_type.lo amqp_exchange.lo amqp_queue.lo amqp_connection.lo amqp_connection_resource.lo amqp_channel.lo amqp_envelope.lo amqp_basic_properties.lo amqp_methods_handling.lo amqp_timestamp.lo amqp_decimal.lo -Wl,-rpath,/usr/usr/lib64 -L/usr/usr/lib64 -lrabbitmq
`

**Comment by lstrojny** [comment] 2023-08-02 21:30
Cannot reproduce this on e.g. latest Debian without further information. Closing for now.

**Closed by lstrojny** 2023-08-02 21:30 UTC
